### ISSUE TITLE
Duplicate entries in command list

### ISSUE THREAD

**Issue by FreeHarry** [volkerdobler/insertnums#15] opened 2024-04-19 08:18 UTC
There are duplicated entries in the command list of VSCode. Two with `extension.insertSeq` and two with `extension.insertNums`. But they are related to the same extension and commands (see screenshot).

I think the entries with `extension.insertNums` can be removed, because the extension is actually named as `Insert Seq`.

![image](https://github.com/volkerdobler/insertnums/assets/24735031/40d82204-7f13-44aa-a083-0637223738ab)

**Comment by volkerdobler** [comment] 2024-04-19 11:04
Hi @FreeHarry, thanks for your post.
To be honest, that is not a bug, it's a feature :-) The original command was "insertnums" when I startet the project, but because of the additional feature (inserting chars, random numbers expressions etc.), I decided to change the name to "insertseq". But changing a name is tricky in marketplaces and because of compatibility reasons, I decided that both names/commands will be possible.
I might change this to "insertseq" in one of the next versions, but currently, you can start the same extension with "insertnums" and "insertseq" and therefore, you see two entries in the list.
Hope that does not getting any problems for you.
Regards,
Volker

**Comment by FreeHarry** [comment] 2024-04-19 13:26
Hi @volkerdobler, ok understood. Makes sense. If this is intended then you can reject this issue. Thanks!

**Comment by volkerdobler** [comment] 2024-04-19 19:37
> Hi @volkerdobler, ok understood. Makes sense. If this is intended then you can reject this issue. Thanks!

Hi will delete one of the commands in the next future. I never tought about this "problem" until you mentioned it, and you are right, it is confusing and I think most users will find the new command or use it already. Thanks, but I will let this issue open until I fixed it (as a reminder for me)

**Comment by volkerdobler** [comment] 2024-04-25 21:44
> There are duplicated entries in the command list of VSCode. Two with `extension.insertSeq` and two with `extension.insertNums`. But they are related to the same extension and commands (see screenshot).
> 
> I think the entries with `extension.insertNums` can be removed, because the extension is actually named as `Insert Seq`.
> 


I just released version 0.9.6 where the old names should be deleted.

**Comment by volkerdobler** [comment] 2024-04-26 15:42
Should be fixed with the new version 0.10.0.

**Closed as completed by volkerdobler** 2024-04-26 15:42 UTC
